# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-23 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_spead', models.TextField(verbose_name='项目进度描述')),
                ('new_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最新更新时间')),
            ],
            options={
                'verbose_name': '项目进度',
                'verbose_name_plural': '项目进度',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('pt_department', models.CharField(max_length=50, verbose_name='项目归属部门')),
                ('bs_situation', models.TextField(verbose_name='基本情况')),
                ('Decision_maker', models.CharField(max_length=20, verbose_name='项目决策人')),
                ('cj_time', models.DateField(default=datetime.datetime.now, verbose_name='预计成交时间')),
                ('xy_support', models.TextField(verbose_name='需要的支持')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司地址')),
                ('bb_people', models.CharField(max_length=20, verbose_name='报备人')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='报备人电话')),
                ('bb_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='报备时间')),
                ('bb_state', models.CharField(choices=[('xzxm', '新增项目'), ('xmjxz', '项目进行中'), ('xmyzz', '项目已终止'), ('zcbbz', '再次报备中')], default='xzxm', max_length=20, verbose_name='报备状态')),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.CompanyName', verbose_name='公司名称')),
                ('kehu_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.KehuUsers', verbose_name='客户名称')),
                ('pt_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basics.ProjectType', verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目报备系统',
                'verbose_name_plural': '项目报备系统',
            },
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.Record', verbose_name='项目名称'),
        ),
    ]
