# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kehu_name',
            field=models.CharField(max_length=20, verbose_name='客户名称'),
        ),
    ]
