# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20180323_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='kehu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.KehuUsers', verbose_name='客户名称'),
        ),
    ]
