# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-23 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('address', models.CharField(max_length=100, verbose_name='公司地址')),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮政编码')),
                ('net_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司网址')),
                ('shengfen', models.CharField(max_length=10, verbose_name='省份')),
                ('cl_data', models.DateField(verbose_name='公司注册时间')),
                ('yyzz_zch', models.CharField(max_length=20, verbose_name='营业执照注册号')),
                ('general_manager', models.CharField(max_length=10, verbose_name='总经理')),
                ('tel', models.CharField(max_length=11, verbose_name='总经理联系方式')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮件地址')),
                ('tech_manager', models.CharField(blank=True, max_length=10, null=True, verbose_name='技术经理')),
                ('tech_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='技术经理联系方式')),
                ('tech_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='技术经理邮件地址')),
                ('mt_manager', models.CharField(blank=True, max_length=10, null=True, verbose_name='市场经理')),
                ('mt_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='市场经理联系方式')),
                ('mt_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='市场经理邮件地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basics.CityDict', verbose_name='所在城市')),
                ('typeenterprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basics.TypeEnterprise', verbose_name='企业类型')),
            ],
            options={
                'verbose_name': '合作企业信息',
                'verbose_name_plural': '合作企业信息',
            },
        ),
        migrations.CreateModel(
            name='KehuUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kehu_name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('Decision_maker', models.CharField(max_length=20, verbose_name='项目决策人')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('desc', models.TextField(verbose_name='客户项目记录')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
